/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author ralu
 */
public class formTasks extends javax.swing.JFrame {

    /**
     * Creates new form formTasks
     */
    public formTasks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Background = new javax.swing.JPanel();
        Form = new javax.swing.JPanel();
        InputDate = new com.toedter.calendar.JDateChooser();
        InputText = new javax.swing.JTextField();
        BtnConfirmUpdate = new javax.swing.JButton();
        IdUpdate = new javax.swing.JLabel();
        BtnAdd = new javax.swing.JButton();
        LayoutTask1 = new javax.swing.JPanel();
        Task1 = new javax.swing.JCheckBox();
        IdTask1 = new javax.swing.JLabel();
        BtnUpdate1 = new javax.swing.JButton();
        BtnDrop1 = new javax.swing.JButton();
        Date1 = new javax.swing.JLabel();
        LayoutTask2 = new javax.swing.JPanel();
        Task2 = new javax.swing.JCheckBox();
        IdTask2 = new javax.swing.JLabel();
        BtnUpdate2 = new javax.swing.JButton();
        BtnDrop2 = new javax.swing.JButton();
        Date2 = new javax.swing.JLabel();
        LayoutTask3 = new javax.swing.JPanel();
        Task3 = new javax.swing.JCheckBox();
        IdTask3 = new javax.swing.JLabel();
        BtnUpdate3 = new javax.swing.JButton();
        BtnDrop3 = new javax.swing.JButton();
        Date3 = new javax.swing.JLabel();
        LayoutTask4 = new javax.swing.JPanel();
        Task4 = new javax.swing.JCheckBox();
        IdTask4 = new javax.swing.JLabel();
        BtnUpdate4 = new javax.swing.JButton();
        BtnDrop4 = new javax.swing.JButton();
        Date4 = new javax.swing.JLabel();
        LayoutTask5 = new javax.swing.JPanel();
        Task5 = new javax.swing.JCheckBox();
        IdTask5 = new javax.swing.JLabel();
        BtnUpdate5 = new javax.swing.JButton();
        BtnDrop5 = new javax.swing.JButton();
        Date5 = new javax.swing.JLabel();
        LayoutTask6 = new javax.swing.JPanel();
        Task6 = new javax.swing.JCheckBox();
        IdTask6 = new javax.swing.JLabel();
        BtnUpdate6 = new javax.swing.JButton();
        BtnDrop6 = new javax.swing.JButton();
        Date6 = new javax.swing.JLabel();
        LayoutTask8 = new javax.swing.JPanel();
        Task8 = new javax.swing.JCheckBox();
        IdTask8 = new javax.swing.JLabel();
        BtnUpdate8 = new javax.swing.JButton();
        BtnDrop8 = new javax.swing.JButton();
        Date8 = new javax.swing.JLabel();
        LayoutTask7 = new javax.swing.JPanel();
        Task7 = new javax.swing.JCheckBox();
        IdTask7 = new javax.swing.JLabel();
        BtnUpdate7 = new javax.swing.JButton();
        BtnDrop7 = new javax.swing.JButton();
        Date7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(51, 51, 51));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Form.setBackground(new java.awt.Color(255, 153, 153));

        InputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTextActionPerformed(evt);
            }
        });

        BtnConfirmUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/updateIcon.png"))); // NOI18N
        BtnConfirmUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConfirmUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmUpdateActionPerformed(evt);
            }
        });

        IdUpdate.setText("0");

        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addIcon.png"))); // NOI18N
        BtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormLayout = new javax.swing.GroupLayout(Form);
        Form.setLayout(FormLayout);
        FormLayout.setHorizontalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(InputText, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(InputDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(BtnConfirmUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        FormLayout.setVerticalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnConfirmUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InputText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IdUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(InputDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        BtnConfirmUpdate.getAccessibleContext().setAccessibleName("Add Task");
        BtnConfirmUpdate.getAccessibleContext().setAccessibleDescription("Add Task");
        BtnAdd.getAccessibleContext().setAccessibleName("Update Task");
        BtnAdd.getAccessibleContext().setAccessibleDescription("Update Task");

        Background.add(Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        LayoutTask1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task1.setBorder(null);
        Task1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task1ActionPerformed(evt);
            }
        });

        IdTask1.setText("0");

        BtnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate1ActionPerformed(evt);
            }
        });

        BtnDrop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask1Layout = new javax.swing.GroupLayout(LayoutTask1);
        LayoutTask1.setLayout(LayoutTask1Layout);
        LayoutTask1Layout.setHorizontalGroup(
            LayoutTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BtnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask1Layout.setVerticalGroup(
            LayoutTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask1Layout.createSequentialGroup()
                .addGroup(LayoutTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdTask1)
                        .addGap(14, 14, 14))
                    .addGroup(LayoutTask1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(LayoutTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnDrop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnUpdate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(Date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Task1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        BtnUpdate1.getAccessibleContext().setAccessibleName("Delete Task1");
        BtnUpdate1.getAccessibleContext().setAccessibleDescription("Delete Task1");
        BtnDrop1.getAccessibleContext().setAccessibleName("Upload Task1");
        BtnDrop1.getAccessibleContext().setAccessibleDescription("Upload Task1");

        Background.add(LayoutTask1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 60));

        LayoutTask2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task2ActionPerformed(evt);
            }
        });

        IdTask2.setText("0");

        BtnUpdate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate2ActionPerformed(evt);
            }
        });

        BtnDrop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask2Layout = new javax.swing.GroupLayout(LayoutTask2);
        LayoutTask2.setLayout(LayoutTask2Layout);
        LayoutTask2Layout.setHorizontalGroup(
            LayoutTask2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BtnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask2Layout.setVerticalGroup(
            LayoutTask2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(IdTask2)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutTask2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnUpdate2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(BtnDrop2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Task2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnUpdate2.getAccessibleContext().setAccessibleName("Delete Task2");
        BtnUpdate2.getAccessibleContext().setAccessibleDescription("Delete Task2");
        BtnDrop2.getAccessibleContext().setAccessibleName("Upload Task2");
        BtnDrop2.getAccessibleContext().setAccessibleDescription("Upload Task2");

        Background.add(LayoutTask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 60));

        LayoutTask3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task3ActionPerformed(evt);
            }
        });

        IdTask3.setText("0");

        BtnUpdate3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate3ActionPerformed(evt);
            }
        });

        BtnDrop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask3Layout = new javax.swing.GroupLayout(LayoutTask3);
        LayoutTask3.setLayout(LayoutTask3Layout);
        LayoutTask3Layout.setHorizontalGroup(
            LayoutTask3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask3Layout.setVerticalGroup(
            LayoutTask3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(IdTask3)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutTask3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnUpdate3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(BtnDrop3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Task3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnUpdate3.getAccessibleContext().setAccessibleName("Delete Task3");
        BtnUpdate3.getAccessibleContext().setAccessibleDescription("Delete Task3");
        BtnDrop3.getAccessibleContext().setAccessibleName("Upload Task3");
        BtnDrop3.getAccessibleContext().setAccessibleDescription("Upload Task3");

        Background.add(LayoutTask3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 800, 60));

        LayoutTask4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task4ActionPerformed(evt);
            }
        });

        IdTask4.setText("0");

        BtnUpdate4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate4ActionPerformed(evt);
            }
        });

        BtnDrop4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask4Layout = new javax.swing.GroupLayout(LayoutTask4);
        LayoutTask4.setLayout(LayoutTask4Layout);
        LayoutTask4Layout.setHorizontalGroup(
            LayoutTask4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnUpdate4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask4Layout.setVerticalGroup(
            LayoutTask4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(IdTask4)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(LayoutTask4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutTask4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDrop4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Task4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnUpdate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnUpdate4.getAccessibleContext().setAccessibleName("Delete Task4");
        BtnUpdate4.getAccessibleContext().setAccessibleDescription("Delete Task4");
        BtnDrop4.getAccessibleContext().setAccessibleName("Upload Task4");
        BtnDrop4.getAccessibleContext().setAccessibleDescription("Upload Task4");

        Background.add(LayoutTask4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 800, 60));

        LayoutTask5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task5ActionPerformed(evt);
            }
        });

        IdTask5.setText("0");

        BtnUpdate5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate5ActionPerformed(evt);
            }
        });

        BtnDrop5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask5Layout = new javax.swing.GroupLayout(LayoutTask5);
        LayoutTask5.setLayout(LayoutTask5Layout);
        LayoutTask5Layout.setHorizontalGroup(
            LayoutTask5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnUpdate5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask5Layout.setVerticalGroup(
            LayoutTask5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(IdTask5)
                .addGap(20, 20, 20))
            .addGroup(LayoutTask5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutTask5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnUpdate5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(BtnDrop5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Task5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnUpdate5.getAccessibleContext().setAccessibleName("Delete Task5");
        BtnUpdate5.getAccessibleContext().setAccessibleDescription("Delete Task5");
        BtnDrop5.getAccessibleContext().setAccessibleName("Upload Task5");
        BtnDrop5.getAccessibleContext().setAccessibleDescription("Upload Task5");

        Background.add(LayoutTask5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 800, 60));

        LayoutTask6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task6ActionPerformed(evt);
            }
        });

        IdTask6.setText("0");

        BtnUpdate6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate6ActionPerformed(evt);
            }
        });

        BtnDrop6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask6Layout = new javax.swing.GroupLayout(LayoutTask6);
        LayoutTask6.setLayout(LayoutTask6Layout);
        LayoutTask6Layout.setHorizontalGroup(
            LayoutTask6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BtnUpdate6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask6Layout.setVerticalGroup(
            LayoutTask6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IdTask6)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutTask6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnDrop6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnUpdate6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LayoutTask6Layout.createSequentialGroup()
                        .addComponent(Task6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Date6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnUpdate6.getAccessibleContext().setAccessibleName("Delete Task6");
        BtnUpdate6.getAccessibleContext().setAccessibleDescription("Delete Task6");
        BtnDrop6.getAccessibleContext().setAccessibleName("Upload Task6");
        BtnDrop6.getAccessibleContext().setAccessibleDescription("Upload Task6");

        Background.add(LayoutTask6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 800, 60));

        LayoutTask8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task8ActionPerformed(evt);
            }
        });

        IdTask8.setText("0");

        BtnUpdate8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate8ActionPerformed(evt);
            }
        });

        BtnDrop8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask8Layout = new javax.swing.GroupLayout(LayoutTask8);
        LayoutTask8.setLayout(LayoutTask8Layout);
        LayoutTask8Layout.setHorizontalGroup(
            LayoutTask8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnUpdate8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask8Layout.setVerticalGroup(
            LayoutTask8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(IdTask8)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(LayoutTask8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutTask8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnUpdate8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(BtnDrop8, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Task8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnUpdate8.getAccessibleContext().setAccessibleName("Delete Task8");
        BtnUpdate8.getAccessibleContext().setAccessibleDescription("Delete Task8");
        BtnDrop8.getAccessibleContext().setAccessibleName("Upload Task8");
        BtnDrop8.getAccessibleContext().setAccessibleDescription("Upload Task8");

        Background.add(LayoutTask8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 800, 60));

        LayoutTask7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Task7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task7ActionPerformed(evt);
            }
        });

        IdTask7.setText("0");

        BtnUpdate7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uploadIcon.png"))); // NOI18N
        BtnUpdate7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate7ActionPerformed(evt);
            }
        });

        BtnDrop7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeIcon.png"))); // NOI18N
        BtnDrop7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDrop7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDrop7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutTask7Layout = new javax.swing.GroupLayout(LayoutTask7);
        LayoutTask7.setLayout(LayoutTask7Layout);
        LayoutTask7Layout.setHorizontalGroup(
            LayoutTask7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutTask7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(IdTask7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Task7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Date7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnUpdate7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BtnDrop7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        LayoutTask7Layout.setVerticalGroup(
            LayoutTask7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutTask7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IdTask7)
                .addGap(20, 20, 20))
            .addGroup(LayoutTask7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutTask7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDrop7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnUpdate7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Task7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnUpdate7.getAccessibleContext().setAccessibleName("Delete Task7");
        BtnUpdate7.getAccessibleContext().setAccessibleDescription("Delete Task7");
        BtnDrop7.getAccessibleContext().setAccessibleName("Upload Task7");
        BtnDrop7.getAccessibleContext().setAccessibleDescription("Upload Task7");

        Background.add(LayoutTask7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 800, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTextActionPerformed

    private void BtnConfirmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConfirmUpdateActionPerformed

    private void Task1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task1ActionPerformed

    private void Task2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task2ActionPerformed

    private void Task3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task3ActionPerformed

    private void Task4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task4ActionPerformed

    private void Task5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task5ActionPerformed

    private void Task6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task6ActionPerformed

    private void Task7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task7ActionPerformed

    private void Task8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Task8ActionPerformed

    private void BtnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate1ActionPerformed

    private void BtnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate2ActionPerformed

    private void BtnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate3ActionPerformed

    private void BtnUpdate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate4ActionPerformed

    private void BtnUpdate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate5ActionPerformed

    private void BtnUpdate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate6ActionPerformed

    private void BtnUpdate7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate7ActionPerformed

    private void BtnUpdate8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdate8ActionPerformed

    private void BtnDrop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop1ActionPerformed

    private void BtnDrop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop2ActionPerformed

    private void BtnDrop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop3ActionPerformed

    private void BtnDrop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop4ActionPerformed

    private void BtnDrop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop5ActionPerformed

    private void BtnDrop6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop6ActionPerformed

    private void BtnDrop7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop7ActionPerformed

    private void BtnDrop8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDrop8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDrop8ActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    public javax.swing.JButton BtnAdd;
    public javax.swing.JButton BtnConfirmUpdate;
    public javax.swing.JButton BtnDrop1;
    public javax.swing.JButton BtnDrop2;
    public javax.swing.JButton BtnDrop3;
    public javax.swing.JButton BtnDrop4;
    public javax.swing.JButton BtnDrop5;
    public javax.swing.JButton BtnDrop6;
    public javax.swing.JButton BtnDrop7;
    public javax.swing.JButton BtnDrop8;
    public javax.swing.JButton BtnUpdate1;
    public javax.swing.JButton BtnUpdate2;
    public javax.swing.JButton BtnUpdate3;
    public javax.swing.JButton BtnUpdate4;
    public javax.swing.JButton BtnUpdate5;
    public javax.swing.JButton BtnUpdate6;
    public javax.swing.JButton BtnUpdate7;
    public javax.swing.JButton BtnUpdate8;
    public javax.swing.JLabel Date1;
    public javax.swing.JLabel Date2;
    public javax.swing.JLabel Date3;
    public javax.swing.JLabel Date4;
    public javax.swing.JLabel Date5;
    public javax.swing.JLabel Date6;
    public javax.swing.JLabel Date7;
    public javax.swing.JLabel Date8;
    private javax.swing.JPanel Form;
    public javax.swing.JLabel IdTask1;
    public javax.swing.JLabel IdTask2;
    public javax.swing.JLabel IdTask3;
    public javax.swing.JLabel IdTask4;
    public javax.swing.JLabel IdTask5;
    public javax.swing.JLabel IdTask6;
    public javax.swing.JLabel IdTask7;
    public javax.swing.JLabel IdTask8;
    public javax.swing.JLabel IdUpdate;
    public com.toedter.calendar.JDateChooser InputDate;
    public javax.swing.JTextField InputText;
    public javax.swing.JPanel LayoutTask1;
    public javax.swing.JPanel LayoutTask2;
    public javax.swing.JPanel LayoutTask3;
    public javax.swing.JPanel LayoutTask4;
    public javax.swing.JPanel LayoutTask5;
    public javax.swing.JPanel LayoutTask6;
    public javax.swing.JPanel LayoutTask7;
    public javax.swing.JPanel LayoutTask8;
    public javax.swing.JCheckBox Task1;
    public javax.swing.JCheckBox Task2;
    public javax.swing.JCheckBox Task3;
    public javax.swing.JCheckBox Task4;
    public javax.swing.JCheckBox Task5;
    public javax.swing.JCheckBox Task6;
    public javax.swing.JCheckBox Task7;
    public javax.swing.JCheckBox Task8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
